### ISSUE TITLE
bash script for fast & flexible pair-wise (ext) camera calibration 

### ISSUE THREAD

**Issue by danishabbir** [stanfordwhil/ErgoLens#11]
Now that we have openpose extrinsic calibration working, we can put together a script to automate all aspects of calibration.

this could be achieved as a bash script

— Set origin cam (Air)

Run these routines:
— KaraCalibrator: Air<->Earth
	put them in the relevant folder
	run crop
	run open pose ext calibration script
	
— KC: Air <-> Water
	put them in the relevant folder
	run crop
	run open pose ext calibration script
	
— KC: Air <-> Fire
	put them in the relevant folder
	run crop
	run open pose ext calibration script

**Comment by vrtejus** [comment]
Done. Need to change after issue #15.
