### ISSUE TITLE
Architect angles module 

### ISSUE THREAD

**Issue by melodyachang** [stanfordwhil/ErgoLens#19]
@danishabbir

**Comment by melodyachang** [comment]
@golrokhme & @danishabbir 
Get the 3D points per frame [done]
Compute vertical reference point for each joint wrt reference jt [done]
Calculate dot & cross product between vector along bone direction & vector from reference point (done)
Get the angle between two vectors [done]
Visualize the reference pts to make sure they're correctly placed in 3d gui [underway]

-
get trunk flexion, lateral bending, etc. 
get neck flexion, bending, etc angles

@samjkwong 
Use tables in published paper to categorize the angles
Compute rula-reba score using script Vishnu has started

**Comment by danishabbir** [comment]
next in angle computation:
* Horizontal angles (top view)
![image](https://user-images.githubusercontent.com/13021858/63407672-ede6fd00-c3a1-11e9-97b2-92ea80313b1d.png)

**Comment by danishabbir** [comment]
* Trunk flexion, lateral bending & axial rotation

![image](https://user-images.githubusercontent.com/13021858/63407709-0b1bcb80-c3a2-11e9-987d-8df23ad2a8af.png)
